### ISSUE TITLE
please create 'stable' branch

### ISSUE THREAD

**Issue by rseuster** [indico/indico-containers#22]
Hi,
with great excitement, I saw this project. At my home university I was missing an indico style system. I was very pleased to see the (docker) container efforts. What I would like to see for the near future is a small demo for university, what indico can give you. A working docker image would be really perfect. For universities, once they support it, it could have a huge impact. Lectures, seminars, everything could be archived in indico. Once agreed, they can pour resources into it.  But it needs a working demo.

So, my current problems is this. After a couple of "docker-compose up" to get all images loaded and so on I get this error:
```
seuster@phastd:~/indico-containers$ docker-compose up
indico-containers_indico-redis_1 is up-to-date
indico-containers_indico-postgres_1 is up-to-date
indico-containers_indico-static_1 is up-to-date
indico-containers_indico-celery_1 is up-to-date
indico-containers_indico-web_1 is up-to-date
Starting indico-containers_indico-nginx_1 ... 

ERROR: for indico-containers_indico-nginx_1  a bytes-like object is required, not 'str'

ERROR: for indico-nginx  a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.22/containers/d3c44f19a7603cc45ead544ed1110ab852cf820ad03c96113270403e232ab55e/start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/compose/service.py", line 625, in start_container
    container.start()
  File "/usr/lib/python3/dist-packages/compose/container.py", line 241, in start
    return self.client.start(self.id, **options)
  File "/usr/lib/python3/dist-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/docker/api/container.py", line 1095, in start
    self._raise_for_status(res)
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/lib/python3/dist-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("b'driver failed programming external connectivity on endpoint indico-containers_indico-nginx_1 (2b7378ddd6e86c9437b65a816ba3f326508ae372ac020476cca861391fc0b2c1): Error starting userland proxy: listen tcp4 0.0.0.0:8080: bind: address already in use'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    load_entry_point('docker-compose==1.25.0', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 72, in main
    command()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 128, in perform_command
    handler(command, command_options)
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 1107, in up
    to_attach = up(False)
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 1088, in up
    return self.project.up(
  File "/usr/lib/python3/dist-packages/compose/project.py", line 565, in up
    results, errors = parallel.parallel_execute(
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 112, in parallel_execute
    raise error_to_reraise
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 210, in producer
    result = func(obj)
  File "/usr/lib/python3/dist-packages/compose/project.py", line 548, in do
    return service.execute_convergence_plan(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 567, in execute_convergence_plan
    return self._execute_convergence_start(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 506, in _execute_convergence_start
    _, errors = parallel_execute(
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 112, in parallel_execute
    raise error_to_reraise
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 210, in producer
    result = func(obj)
  File "/usr/lib/python3/dist-packages/compose/service.py", line 508, in <lambda>
    lambda c: self.start_container_if_stopped(c, attach_logs=not detached, quiet=True),
  File "/usr/lib/python3/dist-packages/compose/service.py", line 620, in start_container_if_stopped
    return self.start_container(container)
  File "/usr/lib/python3/dist-packages/compose/service.py", line 627, in start_container
    if "driver failed programming external connectivity" in ex.explanation:
TypeError: a bytes-like object is required, not 'str'
seuster@phastd:~/indico-containers$ 
```
Seems like a small thing to fix, but an annoying thing for all who try out indico.
Thanks in advance, Rolf

**Comment by rseuster** [comment]
wow - despite this error the web site came up. I m deeply impressed. Keep up the good work !

**Comment by ThiefMaster** [comment]
hi, those errors look like your local docker tools are somewhat broke - none of those errors come from code related to indico...
